### ISSUE TITLE
Fails to retrieve anything with multithreading on

### ISSUE THREAD

**Issue by ahalekelly** [JonathanVusich/pcpartpicker#33]
Thank you for making this! I've had a project I've wanted to do for years that required good price data. Unfortunately the examples from the readme, both `api.retrieve("cpu")` and `api.retrieve_all()` give the following crash, which repeats indefinitely:
```
PS C:\Users\ahale> & C:/Users/ahale/AppData/Local/Programs/Python/Python37-32/python.exe c:/Users/ahale/Documents/pcPartPicker.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\ahale\Documents\pcPartPicker.py", line 3, in <module>
    cpu_data = api.retrieve("cpu")
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pcpartpicker\api.py", line 68, in retrieve     
    return self._handler.retrieve(*args, force_refresh=force_refresh)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pcpartpicker\handler.py", line 110, in retrieve
    parsed_data = parse(raw_data, self._multithreading)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pcpartpicker\parse_utils.py", line 35, in parse
    with Pool() as pool:
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\pool.py", line 241, in _repopulate_pool      
    w.start()
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__  
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\ahale\AppData\Local\Programs\Python\Python37-32\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
With multithreading off it seems to operate normally.

**Comment by JonathanVusich** [comment]
You're welcome! I see that you are using Python 3.7.2....as I recall this specific version has a bug in its implementation of the multiprocessing pool that causes it to throw errors. Python 3.7.3 and 3.7.1 should work fine. Not sure about Python 3.7.4.

**Comment by ahalekelly** [comment]
Huh weird. I forgot to mention that I had tried upgrading from 3.7.2 to 3.7.4 before posting the issue, with the same results, I think the log above was actually from 3.7.4. Just installed 3.7.1 and I'm getting the same error.

It really doesn't matter though, the API returns pretty much instantly single threaded. Just took a bit of time to figure out. Maybe change the default setting?

**Comment by JonathanVusich** [comment]
Out of curiosity, I noticed that you are using 32 bit Python. Do you mind trying 64 bit Python? It would be nice to know the trigger so that I know best how to address it.

**Comment by ahalekelly** [comment]
Yep when I installed 3.7.1 it was the 64 bit version. Just tested 3.6.8 64 bit on Windows as well, no luck, but 3.6.8 on WSL Ubuntu runs fine.

**Comment by JonathanVusich** [comment]
Yeah, I develop on Windows. That's really odd. At any rate, I'm thinking about just pulling multithreading from this entirely. It used to be helpful when this API would scrape and process all the data by itself, but now it's probably  not necessary.

**Comment by ahalekelly** [comment]
Oh no I can't hide my typo
This seems a lot easier than pulling it entirely
